/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTrashRouteImport } from './routes/_auth.trash'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthMoreRouteImport } from './routes/_auth.more'
import { Route as AuthLibraryRouteImport } from './routes/_auth.library'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthAboutRouteImport } from './routes/_auth.about'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth.settings.profile'
import { Route as AuthSettingsPreferencesRouteImport } from './routes/_auth.settings.preferences'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTrashRoute = AuthTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMoreRoute = AuthMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLibraryRoute = AuthLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAboutRoute = AuthAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsPreferencesRoute = AuthSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AuthSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof AuthAboutRoute
  '/dashboard': typeof AuthDashboardRoute
  '/library': typeof AuthLibraryRoute
  '/more': typeof AuthMoreRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/trash': typeof AuthTrashRoute
  '/settings/preferences': typeof AuthSettingsPreferencesRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof AuthAboutRoute
  '/dashboard': typeof AuthDashboardRoute
  '/library': typeof AuthLibraryRoute
  '/more': typeof AuthMoreRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/trash': typeof AuthTrashRoute
  '/settings/preferences': typeof AuthSettingsPreferencesRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_auth/about': typeof AuthAboutRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/library': typeof AuthLibraryRoute
  '/_auth/more': typeof AuthMoreRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/trash': typeof AuthTrashRoute
  '/_auth/settings/preferences': typeof AuthSettingsPreferencesRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/dashboard'
    | '/library'
    | '/more'
    | '/settings'
    | '/trash'
    | '/settings/preferences'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/dashboard'
    | '/library'
    | '/more'
    | '/settings'
    | '/trash'
    | '/settings/preferences'
    | '/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/sign-in'
    | '/sign-up'
    | '/_auth/about'
    | '/_auth/dashboard'
    | '/_auth/library'
    | '/_auth/more'
    | '/_auth/settings'
    | '/_auth/trash'
    | '/_auth/settings/preferences'
    | '/_auth/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/trash': {
      id: '/_auth/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthTrashRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/more': {
      id: '/_auth/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthMoreRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/library': {
      id: '/_auth/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthLibraryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/about': {
      id: '/_auth/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthAboutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/preferences': {
      id: '/_auth/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthSettingsPreferencesRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
  }
}

interface AuthSettingsRouteChildren {
  AuthSettingsPreferencesRoute: typeof AuthSettingsPreferencesRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsPreferencesRoute: AuthSettingsPreferencesRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthAboutRoute: typeof AuthAboutRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthLibraryRoute: typeof AuthLibraryRoute
  AuthMoreRoute: typeof AuthMoreRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthTrashRoute: typeof AuthTrashRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAboutRoute: AuthAboutRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthLibraryRoute: AuthLibraryRoute,
  AuthMoreRoute: AuthMoreRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthTrashRoute: AuthTrashRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
